apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: kowthar-inc
  labels: 
    name: gateway
    app: gateway

spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 3
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: gateway
          image: gitlab.abrbit.com:5555/camelon/kowthar-gateway/master:stable
          imagePullPolicy: Always
          env:
            - name: CDN_PREFIX
              value: http://kins-gateway.abrbit.com/
            - name: DB_DNS
              value: root:FbRLAQmx2m@tcp(mariadb.kowthar-inc.svc.cluster.local:3306)/kowthar_ins?charset=utf8&parseTime=True&loc=Local
          ports:
            - containerPort: 8080
              protocol: TCP

          volumeMounts:
            - name: kowthar-storage
              mountPath: /app/media/storage/

      volumes:
        - name: kowthar-storage
          persistentVolumeClaim:
            claimName: cephfs-pvc
            readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: kowthar-inc
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  namespace: kowthar-inc
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kins-gateway.abrbit.com
    http:
      paths:
      - backend:
          serviceName: gateway-service
          servicePort: 8080
