import { getStatusChoicesTitle } from "./damage";

export const fields = {
    'Status': 'وضعیت',
    'AcceptedAmount': 'مبلغ مورد تایید',
    'ExpertUpdatedAt': 'تاریخ کارشناسی',
    'ExpertStatus': 'تایید کارشناس',
    'ExpertAcceptedAmount': 'مبلغ مورد تایید کارشناس',
    'ExpertDescription': 'توضیحات کارشناس',
    'LackDataDescription': 'نقص مدارک',
    'BillIdentifier': 'شناسه قبض',
    'ReferenceCode': 'کد رهگیری',
    'NationalCode': 'کد ملی',
    'SubscriberType': 'نوع مشترک',
    'Firstname': 'نام',
    'MobileNumber': 'همراه',
    'Address': 'آدرس',
    'PostalAddress': 'کد پستی',
    'Sheba': 'شماره شبا',
    'SumDamageAmount': 'مبلغ خسارت مورد ادعا',
    'Description': 'توضیحات',
    'CasualityDate': 'تاریخ حادثه',
    'CasualityTime': 'ساعت حادثه',
    'IdCardPhoto': 'تصویر کارت ملی',
    'LastBillPhoto': 'آخرین قبض پرداختی',
    'IdCardPhoto': 'سند مالکیت',
    'FiringPlace_1Photo': 'تصویر محل حادثه (1)',
    'FiringPlace_2Photo': 'تصویر محل حادثه (2)',
    'FiringStationReportPhoto': 'تصویر گزارش آتش نشانی (1)',
    'FiringPoliceReportPhoto': 'تصویر گزارش کلانتری',
    'FiringCourtReportPhoto': 'تصویر پرونده دادگاه در صورت شکایت',
    'FiringInvoice_1Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز ۱',
    'FiringInvoice_2Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز ۲',
    'FiringInvoice_3Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز ۳',
    'FiringInvoice_4Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز ۴',
    'FiringInvoice_5Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز ۵',
    'InstrumentInvoicePhoto': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز',
    'InstrumentInvoice_2Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز',
    'InstrumentInvoice_3Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز',
    'InstrumentInvoice_4Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز',
    'InstrumentInvoice_5Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز',
    'InstrumentInvoice_6Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز',
    'InstrumentInvoice_7Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز',
    'InstrumentInvoice_8Photo': 'تصویر فاکتور فروشگاه یا تعمیرگاه مجاز',
    'InstrumentReportPhoto': 'تصویر گزارش معتمدین محل یا نیروی انتظامی',
    'ExplostionDamagedItemsPhoto': 'تصویر لیست موارد آسیب دیده',
    'ExplosionInvoicePhoto': 'تصویر فاکتور تعمیرات',
    'ExplosionPlace_1Photo': 'تصویر محل حادثه (1)',
    'ExplosionPlace_2Photo': 'تصویر محل حادثه (2)',
    'MedicalHospitalInvoicePhoto': 'تصویر اصل صورت حساب بیمارستان',
    'MedicalHospitalDocumentPhoto': 'تصویر مدارک پزشکی و پرونده های بیمارستانی',
    'MedicalReportPhoto': 'تصویر گزارش مقامات ذیصلاح',
    'LackReportPhoto': 'گزارش انتظامی یا بازرس آتش نشانی',
    'LackRadiologyPhoto': 'رادیولوژی بعد از حادثه',
    'LackFirstReferencePhoto': 'اولین مرجع درمانی پزشکی معالج',
    'LackIdCardPhoto': 'کپی کارت ملی، شناسنامه مصدوم',
    'LackWitnessPhoto': 'گواهی پزشک معالج',
    'LackInvoicePhoto': 'صورت حساب پزشکی پرونده مصدوم',
    'DeathJudgeVotePhoto': 'تصویر رای قاضی',
    'DeathWitnessPhoto': 'گواهی فوت',
    'DeathIdCardPhoto': 'شناسنامه ابطال شده، کارت ملی',
    'DeathToxicologyReportPhoto': 'گزارش پزشک قانونی',
    'DeathCorpseExaminationPhoto': 'تصویر معاینه جسد',
    'DeathProbatePhoto': 'گواهی انحصار وراثت',
}

export const getFieldTitle = (f) => {
    return fields[f] || getStatusChoicesTitle(f) || f ;
}